/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AuroraBackofficeToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuroraTenantSetupDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Auth0ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "GrafanaLokiAuth": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OtelFirehoseBackup": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "StripePriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserFilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserInfoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebsiteBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}