/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AcceptInvitation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AccountDeletionDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AccountDeletionSweeper": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AccountDeletionWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ActivateSubscription": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AuditLog": {
      "name": string
      "type": "sst.sst.Linkable"
    }
    "AuditTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AuroraBackofficeToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtRuntimeClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AuthCallback": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthLogin": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthLogout": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BulkDeleteDlq": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BulkDeleteDlqWatchdog": {
      "name": string
      "type": "sst.aws.Function"
    }
    "BulkDeleteQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "BulkDeleteTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "BulkDeleteWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ChangePassword": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ConfirmAccountDeletion": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateAccessKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateBulkDeleteJob": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateInvitation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreatePortalSession": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateRagApiKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "CreateSetupIntent": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteAccessKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteMfaEnrollment": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeletePasskey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeleteRagApiKey": {
      "name": string
      "type": "sst.aws.Function"
    }
    "DeletionChallengeTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "DeletionCodeHmacKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DisableMfa": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EnrollMfa": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ExportAuditEvents": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ForgeDevManagementApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ForgeManagementApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FthManagementApiToken": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GetActivity": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBilling": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBucketAnalytics": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBucketRagEnablement": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetBulkDeleteJob": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetMe": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetPreferences": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetUsage": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GetUsageTrends": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GracePeriodEnforcer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "GrafanaLokiAuth": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HubSpotContactSync": {
      "name": string
      "type": "sst.aws.Function"
    }
    "HubSpotServiceKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ListAccessKeys": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListAuditEvents": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListBuckets": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListInvitations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListInvoices": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListMembers": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ListRagApiKeys": {
      "name": string
      "type": "sst.aws.Function"
    }
    "OrgLogoBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "OrgTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "OtelFirehoseBackup": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "OwnerCountDriftChecker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Presign": {
      "name": string
      "type": "sst.aws.Function"
    }
    "QueryBucket": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RagIndexerOrchestrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RagIndexerTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "RagIndexerWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RagVectorBucket": {
      "arn": string
      "name": string
      "type": "sst.sst.Linkable"
    }
    "RegenerateRecoveryCode": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RemoveMember": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RequestAccountDeletion": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ResendVerification": {
      "name": string
      "type": "sst.aws.Function"
    }
    "RevokeInvitation": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SetBucketRagEnablement": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SetupIntegrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripePriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripePublishableKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeWebhook": {
      "name": string
      "type": "sst.aws.Function"
    }
    "SubscriptionDriftChecker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "TransferOwnership": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateMemberRole": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateOrg": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdatePreferences": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UpdateProfile": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UsageReportingOrchestrator": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UsageReportingWorker": {
      "name": string
      "type": "sst.aws.Function"
    }
    "UserFilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "UserInfoTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "WebsiteBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "WebsiteRouter": {
      "type": "sst.aws.Router"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}