/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "Auth0ClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0ClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Auth0MgmtClientSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BillingTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "SetupIntegrations": {
      "name": string
      "type": "sst.aws.Function"
    }
    "StripePriceId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StripeSecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UploadsTable": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "UserFilesBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Website": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}