/* This file is automatically regenerated by `pnpx sst types`.
   Manual version below provides types before first deploy. */
import "sst";

declare module "sst" {
  export interface Resource {
    UploadsTable: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    BillingTable: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    UserFilesBucket: {
      name: string;
      type: "sst.aws.Bucket";
    };
    Auth0ClientId: {
      value: string;
      type: "sst.Secret";
    };
    Auth0ClientSecret: {
      value: string;
      type: "sst.Secret";
    };
    Auth0MgmtClientId: {
      value: string;
      type: "sst.Secret";
    };
    Auth0MgmtClientSecret: {
      value: string;
      type: "sst.Secret";
    };
    StripeSecretKey: {
      value: string;
      type: "sst.Secret";
    };
    StripePriceId: {
      value: string;
      type: "sst.Secret";
    };
    AuroraBackofficeToken: {
      value: string;
      type: "sst.Secret";
    };
    UserInfoTable: {
      name: string;
      type: "sst.aws.Dynamo";
    };
    AuroraTenantSetupQueue: {
      url: string;
      type: "sst.aws.Queue";
    };
    BillingTrialSetupQueue: {
      url: string;
      type: "sst.aws.Queue";
    };
  }
}
