export const OrgSetupStatus = {
  HYPERSPACE_ORG_CREATED: 'HYPERSPACE_ORG_CREATED',
  AURORA_TENANT_CREATED: 'AURORA_TENANT_CREATED',
  AURORA_TENANT_SETUP_COMPLETE: 'AURORA_TENANT_SETUP_COMPLETE',
} as const;
